#!/bin/bash
# save as: verify_structure.sh

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

check() {
  if [ -f "$1" ]; then
    echo -e "${GREEN}✓${NC} $1"
  else
    echo -e "${RED}✗ MISSING: $1${NC}"
  fi
}

echo "=== Root ==="
check ".env.example"
check ".gitignore"
check "docker-compose.yml"
check "README.md"

echo ""
echo "=== Backend Core ==="
check "backend/docker/Dockerfile"
check "backend/requirements.txt"
check "backend/pyproject.toml"
check "backend/alembic.ini"
check "backend/alembic/env.py"
check "backend/alembic/script.py.mako"
check "backend/alembic/versions/001_initial_schema.py"

echo ""
echo "=== Backend App ==="
check "backend/app/__init__.py"
check "backend/app/main.py"
check "backend/app/config.py"
check "backend/app/database.py"
check "backend/app/dependencies.py"

echo ""
echo "=== Models ==="
check "backend/app/models/__init__.py"
check "backend/app/models/user.py"
check "backend/app/models/project.py"
check "backend/app/models/scan.py"
check "backend/app/models/vulnerability.py"
check "backend/app/models/report.py"
check "backend/app/models/taint_flow.py"

echo ""
echo "=== Schemas ==="
check "backend/app/schemas/__init__.py"
check "backend/app/schemas/user.py"
check "backend/app/schemas/project.py"
check "backend/app/schemas/scan.py"
check "backend/app/schemas/vulnerability.py"
check "backend/app/schemas/report.py"

echo ""
echo "=== Core Engine ==="
check "backend/app/core/__init__.py"
check "backend/app/core/ast_parser.py"
check "backend/app/core/scanner.py"
check "backend/app/core/scoring.py"
check "backend/app/core/taint_analysis.py"
check "backend/app/core/data_flow.py"

echo ""
echo "=== Detectors ==="
check "backend/app/core/detectors/__init__.py"
check "backend/app/core/detectors/base.py"
check "backend/app/core/detectors/sql_injection.py"
check "backend/app/core/detectors/xss.py"
check "backend/app/core/detectors/command_injection.py"
check "backend/app/core/detectors/secrets.py"
check "backend/app/core/detectors/weak_crypto.py"
check "backend/app/core/detectors/deserialization.py"
check "backend/app/core/detectors/unsafe_eval.py"
check "backend/app/core/detectors/path_traversal.py"

echo ""
echo "=== AI ==="
check "backend/app/ai/__init__.py"
check "backend/app/ai/prompts.py"
check "backend/app/ai/openai_client.py"
check "backend/app/ai/response_parser.py"

echo ""
echo "=== Services ==="
check "backend/app/services/__init__.py"
check "backend/app/services/auth_service.py"
check "backend/app/services/scan_service.py"
check "backend/app/services/report_service.py"
check "backend/app/services/github_service.py"
check "backend/app/services/docker_service.py"

echo ""
echo "=== API Routes ==="
check "backend/app/api/__init__.py"
check "backend/app/api/v1/__init__.py"
check "backend/app/api/v1/auth.py"
check "backend/app/api/v1/projects.py"
check "backend/app/api/v1/scans.py"
check "backend/app/api/v1/vulnerabilities.py"
check "backend/app/api/v1/reports.py"
check "backend/app/api/v1/github.py"
check "backend/app/api/v1/analytics.py"
check "backend/app/api/v1/sandbox.py"

echo ""
echo "=== Reporting ==="
check "backend/app/reporting/__init__.py"
check "backend/app/reporting/pdf_generator.py"
check "backend/app/reporting/charts.py"

echo ""
echo "=== Tasks ==="
check "backend/app/tasks/__init__.py"
check "backend/app/tasks/scan_tasks.py"
check "backend/app/tasks/report_tasks.py"
check "backend/app/tasks/github_tasks.py"

echo ""
echo "=== Utils ==="
check "backend/app/utils/__init__.py"
check "backend/app/utils/security.py"
check "backend/app/utils/helpers.py"
check "backend/app/utils/zip_handler.py"

echo ""
echo "=== Tests ==="
check "backend/tests/__init__.py"
check "backend/tests/conftest.py"
check "backend/tests/test_detectors/__init__.py"
check "backend/tests/test_detectors/test_all_detectors.py"
check "backend/tests/test_detectors/test_scanner.py"
check "backend/tests/samples/vulnerable_app.py"

echo ""
echo "=== Frontend Core ==="
check "frontend/Dockerfile"
check "frontend/package.json"
check "frontend/tsconfig.json"
check "frontend/tailwind.config.ts"
check "frontend/postcss.config.js"
check "frontend/next.config.js"
check "frontend/next-env.d.ts"
check "frontend/src/styles/globals.css"
check "frontend/src/lib/api.ts"
check "frontend/src/lib/utils.ts"

echo ""
echo "=== Frontend Pages ==="
check "frontend/src/app/layout.tsx"
check "frontend/src/app/page.tsx"
check "frontend/src/app/login/page.tsx"
check "frontend/src/app/register/page.tsx"
check "frontend/src/app/dashboard/layout.tsx"
check "frontend/src/app/dashboard/page.tsx"
check "frontend/src/app/dashboard/projects/page.tsx"
check "frontend/src/app/dashboard/projects/[id]/page.tsx"
check "frontend/src/app/dashboard/scans/page.tsx"
check "frontend/src/app/dashboard/scans/[id]/page.tsx"
check "frontend/src/app/dashboard/reports/page.tsx"
check "frontend/src/app/dashboard/github/page.tsx"
check "frontend/src/app/auth/github/callback/page.tsx"
check "frontend/src/app/auth/github/callback/CallbackContent.tsx"

echo ""
echo "=== Frontend Components ==="
check "frontend/src/components/QueryProvider.tsx"
check "frontend/src/components/layout/Sidebar.tsx"
check "frontend/src/components/scans/FileUploadScanner.tsx"
check "frontend/src/components/scans/SandboxTestPanel.tsx"
check "frontend/src/components/dashboard/RiskScoreCard.tsx"
check "frontend/src/components/dashboard/VulnerabilityChart.tsx"
check "frontend/src/components/dashboard/SeverityBarChart.tsx"
check "frontend/src/components/dashboard/TrendGraph.tsx"
check "frontend/src/components/dashboard/ImprovementCard.tsx"
check "frontend/src/components/dashboard/ScanComparison.tsx"

echo ""
echo "=== CI/CD ==="
check ".github/workflows/backend-ci.yml"
check ".github/workflows/frontend-ci.yml"
check ".github/workflows/security-scan.yml"

echo ""
echo "=== Docs ==="
check "docs/API.md"

echo ""
echo "=== Total files checked ==="